### ISSUE TITLE
TOPS-20 file names, timestamps, etc

### ISSUE THREAD

**Issue by larsbrinkhoff** [historicalsource/zork#1]
Hello,

Do you have file metadata available?  Such as the original TOPS-20 file names and timestamps?

**Comment by larsbrinkhoff** [comment]
For your information, the file contents are identical to this:  
https://github.com/PDP-10/its/tree/master/src/zork

Which is mostly from Bob Supnik's 1981 copy.

**Comment by historicalsource** [comment]
Additional file metadata is not available; it passed through too many machines being converted..
